### ISSUE TITLE
assert by login

### ISSUE THREAD

**Issue by kalapanga** [sergiorykov/TheOdnoklassniki#1]
ruby program.rb
C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': element not vi
sible (Selenium::WebDriver::Error::ElementNotVisibleError)
  (Session info: chrome=50.0.2661.75)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:34:in`initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in`create_res
ponse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:59:in`call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:627:in`execute'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:389:in `clickElement'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/element.rb:73:in`click'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:128:in `block in click'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:598:in`element_call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:117:in `click'
        from D:/Downloads/TheOdnoklassniki-master/odnoklassniki_client.rb:27:in`login'
        from program.rb:11:in `<main>'

**Comment by sergiorykov** [comment]
It seems they changed controls. 

It's just a sample that worked for me pretty well and I don't plan to support it. It played it's role according to readme :). 

It's better to use official API and search for real client.
